import type { AccessDefinitionInput, AccessRegistry } from '../access/access.types';
import type { ParameterComponentInput, ParameterComponentRegistry, RequestBodyComponentInput, RequestBodyComponentRegistry, ResponseComponentInput, ResponseComponentRegistry, SchemaComponentRegistry, SchemaComponentValue } from '../components/component.types';
import type { AuthoringState } from '../core/authoring.types';
import type { BaseEntityDefinitionInput, ConcreteEntityDefinitionInput, EntityDefinitionFactory, EntityRegistry } from '../entities/entity.types';
import type { DefineFrontendOptions, FrontendBuilder } from '../frontend/frontend.types';
import type { PropertyGroupOptions, PropertyRegistry, ZodPropertyDefinitionFieldMap } from '../properties/property.types';
import type { DefineResourceOptions, ResourceBuilder } from '../resource/resource.types';
import type { RouteResponseInput } from '../routes/route.types';
export interface VersionLicense { readonly name: string; readonly identifier?: string; readonly url?: string; }
export interface VersionInfo { readonly title: string; readonly version: string; readonly description?: string; readonly license?: VersionLicense; }
export interface VersionDefaults { readonly requestContentType?: string | readonly string[]; readonly responseContentType?: string | readonly string[]; }
export interface VersionContract { readonly info: VersionInfo; readonly tags: string[]; readonly defaults: VersionDefaults; readonly state: AuthoringState; readonly resources: ResourceBuilder[]; readonly properties: PropertyRegistry[]; readonly schemaComponents: SchemaComponentRegistry[]; readonly parameterComponents: ParameterComponentRegistry[]; readonly requestBodyComponents: RequestBodyComponentRegistry[]; readonly responseComponents: ResponseComponentRegistry[]; readonly accessComponents: AccessRegistry[]; readonly baseEntityComponents: EntityRegistry[]; readonly entityComponents: EntityRegistry[]; readonly frontends: FrontendBuilder[]; readonly defaultResponses: Record<number, RouteResponseInput>; }
export interface DefineVersionContractOptions { readonly info: VersionInfo; readonly tags?: readonly string[]; readonly defaults?: VersionDefaults; readonly resources?: readonly ResourceBuilder[]; }
export interface VersionBuilder { readonly contract: VersionContract; readonly schemas: SchemaComponentRegistry; readonly properties: PropertyRegistry[]; readonly accessComponents: AccessRegistry[]; readonly baseEntityComponents: EntityRegistry[]; readonly entityComponents: EntityRegistry[]; readonly frontends: FrontendBuilder[]; defineResource(options: DefineResourceOptions): ResourceBuilder; addResource(resource: ResourceBuilder): VersionBuilder; addProperties(properties: PropertyRegistry): VersionBuilder; defineProperties<TName extends string, TFields extends ZodPropertyDefinitionFieldMap>(name: TName, fields: TFields, options?: PropertyGroupOptions): ReturnType<typeof import('../properties/define-properties').defineProperties<TName, TFields>>; defineSchemas<const TInput extends Record<string, SchemaComponentValue>>(input: TInput, name?: string): SchemaComponentRegistry<TInput>; defineParameters<const TInput extends Record<string, ParameterComponentInput>>(input: TInput, name?: string): ParameterComponentRegistry<TInput>; defineRequestBodies<const TInput extends Record<string, RequestBodyComponentInput>>(input: TInput, name?: string): RequestBodyComponentRegistry<TInput>; defineResponses<const TInput extends Record<string, ResponseComponentInput>>(input: TInput, name?: string): ResponseComponentRegistry<TInput>; defineAccess<const TInput extends Record<string, AccessDefinitionInput>>(input: TInput): AccessRegistry<TInput>; defineBaseEntities<const TInput extends Record<string, BaseEntityDefinitionInput>>(input: TInput | EntityDefinitionFactory<TInput>): EntityRegistry<TInput>; defineEntities<const TInput extends Record<string, ConcreteEntityDefinitionInput>>(input: TInput | EntityDefinitionFactory<TInput>): EntityRegistry<TInput>; defineFrontend(options: DefineFrontendOptions): FrontendBuilder; tags(tags: readonly string[]): VersionBuilder; setDefaultResponses(responses: Record<number, RouteResponseInput>): VersionBuilder; }
