"""Shared contracts between app, inference, languages, and emission.

Contracts define stable boundaries. Implementation packages may import
contracts, but contracts must not import implementation packages.
"""

from archives.codepotg.src.contracts.api import (
    ApiContract,
    ApiDocumentInfo,
    ApiEnumValue,
    ApiField,
    ApiOperation,
    ApiParameter,
    ApiRequestBody,
    ApiResource,
    ApiResponse,
    ApiSchema,
)
from archives.codepotg.src.contracts.emission import EmissionFile, EmissionPlan, EmissionResult, EmissionWriteResult
from archives.codepotg.src.contracts.events import EventLevel, ProgressSink, RuntimeEvent
from archives.codepotg.src.contracts.language import LanguageAdapter, LanguagePostAction, LanguagePostResult
from archives.codepotg.src.contracts.names import NameSet
from archives.codepotg.src.contracts.source import FrozenMap, freeze_source_map, freeze_source_value, thaw_source_value
from archives.codepotg.src.contracts.template import (
    TemplateContract,
    TemplateContractMeta,
    TemplateDependency,
    TemplateDocs,
    TemplateEmit,
    TemplateFeatures,
    TemplateField,
    TemplateFieldLang,
    TemplateFieldMeta,
    TemplateFile,
    TemplateFramework,
    TemplateFrontend,
    TemplateFrontendComponent,
    TemplateFrontendOperationUse,
    TemplateFrontendScreen,
    TemplateGroup,
    TemplateItemEmit,
    TemplateItemKey,
    TemplateLanguage,
    TemplateOperation,
    TemplateOperationLang,
    TemplateOperationMeta,
    TemplatePackage,
    TemplateParameter,
    TemplateParameterLang,
    TemplateParameterMeta,
    TemplateProject,
    TemplateProjectEmit,
    TemplateProjectLang,
    TemplateRequestBody,
    TemplateRequestBodyLang,
    TemplateRequestBodyMeta,
    TemplateResource,
    TemplateResourceLang,
    TemplateResourceMeta,
    TemplateResponse,
    TemplateResponseLang,
    TemplateResponseMeta,
    TemplateSchema,
    TemplateSchemaGroups,
    TemplateSchemaLang,
    TemplateSchemaMeta,
)

__all__ = [
    "ApiContract",
    "ApiDocumentInfo",
    "ApiEnumValue",
    "ApiField",
    "ApiOperation",
    "ApiParameter",
    "ApiRequestBody",
    "ApiResource",
    "ApiResponse",
    "ApiSchema",
    "EmissionFile",
    "EmissionPlan",
    "EmissionResult",
    "EmissionWriteResult",
    "EventLevel",
    "FrozenMap",
    "LanguageAdapter",
    "LanguagePostAction",
    "LanguagePostResult",
    "NameSet",
    "ProgressSink",
    "RuntimeEvent",
    "TemplateContract",
    "TemplateContractMeta",
    "TemplateDependency",
    "TemplateDocs",
    "TemplateEmit",
    "TemplateFeatures",
    "TemplateField",
    "TemplateFieldLang",
    "TemplateFieldMeta",
    "TemplateFile",
    "TemplateFramework",
    "TemplateFrontend",
    "TemplateFrontendComponent",
    "TemplateFrontendOperationUse",
    "TemplateFrontendScreen",
    "TemplateGroup",
    "TemplateItemEmit",
    "TemplateItemKey",
    "TemplateLanguage",
    "TemplateOperation",
    "TemplateOperationLang",
    "TemplateOperationMeta",
    "TemplatePackage",
    "TemplateParameter",
    "TemplateParameterLang",
    "TemplateParameterMeta",
    "TemplateProject",
    "TemplateProjectEmit",
    "TemplateProjectLang",
    "TemplateRequestBody",
    "TemplateRequestBodyLang",
    "TemplateRequestBodyMeta",
    "TemplateResource",
    "TemplateResourceLang",
    "TemplateResourceMeta",
    "TemplateResponse",
    "TemplateResponseLang",
    "TemplateResponseMeta",
    "TemplateSchema",
    "TemplateSchemaGroups",
    "TemplateSchemaLang",
    "TemplateSchemaMeta",
    "freeze_source_map",
    "freeze_source_value",
    "thaw_source_value",
]
