packages:
  - apps/*
  - packages/nodejs/codepotx
  - packages/nodejs/codepotx-cli
  - packages/nodejs/codepot-openapi

allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - esbuild
