"""Typed Python authoring compiler for the CodepotG v2 semantic IR."""

from .author import Author
from .compiler import AuthoringResult, compile_author
from .diagnostics import AUTHOR_CORE_UNSUPPORTED, AuthorDiagnostic, AuthorDiagnostics, AuthorDiagnosticSeverity
from .options import AuthorOptions, UnsupportedCorePolicy
from .pydantic import PydanticCompiler
from .refs import (
    EventRef,
    FieldRef,
    GroupRef,
    OperationRef,
    PolicyRef,
    PresentationRef,
    PropertyRef,
    Ref,
    RefIdentity,
    RefKind,
    RefUsage,
    SchemaRef,
    StorageRef,
    ValueSourceRef,
    ViewRef,
    WorkflowRef,
    WorkflowStepRef,
)
from .schemas import (
    FieldDeclaration,
    FieldOptions,
    FieldSpec,
    ProjectionStep,
    PropertyDeclaration,
    SchemaDeclaration,
    SchemaDeclarationKind,
    field,
    schema_field,
)
from .semantics import (
    EventDeclaration,
    OperationDeclaration,
    OperationFailureDeclaration,
    OperationOutputDeclaration,
    PolicyDeclaration,
    SchemaUseDeclaration,
    StorageDeclaration,
    StorageFieldDeclaration,
    ViewDeclaration,
    ViewTriggerDeclaration,
    WorkflowDeclaration,
    WorkflowStepDeclaration,
)
from .transport import (
    FORMAT,
    VERSION,
    dumps_json,
    dumps_yaml,
    loads_json,
    loads_yaml,
)

__version__ = "0.1.0a1"

__all__ = [
    "AUTHOR_CORE_UNSUPPORTED",
    "FORMAT",
    "VERSION",
    "Author",
    "AuthorDiagnostic",
    "AuthorDiagnostics",
    "AuthorDiagnosticSeverity",
    "AuthorOptions",
    "AuthoringResult",
    "EventDeclaration",
    "EventRef",
    "FieldDeclaration",
    "FieldOptions",
    "FieldRef",
    "FieldSpec",
    "GroupRef",
    "OperationDeclaration",
    "OperationFailureDeclaration",
    "OperationOutputDeclaration",
    "OperationRef",
    "PolicyDeclaration",
    "PolicyRef",
    "PresentationRef",
    "ProjectionStep",
    "PropertyDeclaration",
    "PropertyRef",
    "PydanticCompiler",
    "Ref",
    "RefIdentity",
    "RefKind",
    "RefUsage",
    "SchemaDeclaration",
    "SchemaDeclarationKind",
    "SchemaRef",
    "SchemaUseDeclaration",
    "StorageDeclaration",
    "StorageFieldDeclaration",
    "StorageRef",
    "UnsupportedCorePolicy",
    "ValueSourceRef",
    "ViewDeclaration",
    "ViewRef",
    "ViewTriggerDeclaration",
    "WorkflowDeclaration",
    "WorkflowRef",
    "WorkflowStepDeclaration",
    "WorkflowStepRef",
    "compile_author",
    "dumps_json",
    "dumps_yaml",
    "field",
    "loads_json",
    "loads_yaml",
    "schema_field",
    "__version__",
]
