from .compiler import AuthoringResult, compile_author

PIPELINE = ("REGISTER", "VALIDATE_DECLARATIONS", "RESOLVE_REFERENCES", "RESOLVE_DERIVED_AUTHORING", "COMPILE_FEATURES", "ASSEMBLE_GROUPS", "CREATE_CONTRACT", "CANONICAL_IR_VALIDATION")

__all__ = ["AuthoringResult", "PIPELINE", "compile_author"]
