from .core import (
    CORE_VERSION,
    IR_VERSION,
    NAMING_BEHAVIOR_VERSION,
    PLANNING_BEHAVIOR_VERSION,
    PLUGIN_API_VERSION,
    PUBLIC_API_VERSION,
    SELECTION_BEHAVIOR_VERSION,
    ApiVersion,
    BehaviorVersion,
    CancellationToken,
    Diagnostic,
    DiagnosticSeverity,
    Diagnostics,
    OperationCancelled,
    OperationResult,
    OperationStatus,
    SemanticVersion,
    SourceIdentity,
    SourceKind,
    SourcePosition,
    SourceSpan,
)
from .ir import Contract, Group, Operation, Schema, SemanticId
from .naming import Name, NameProjection
from .plugins import PluginCategory, PluginDescriptor, PluginRegistry, PluginTrust
from .validation import ContractValidator, validate_contract

__version__ = str(CORE_VERSION)

__all__ = [
    "ApiVersion",
    "BehaviorVersion",
    "CORE_VERSION",
    "CancellationToken",
    "Contract",
    "ContractValidator",
    "Diagnostic",
    "DiagnosticSeverity",
    "Diagnostics",
    "Group",
    "IR_VERSION",
    "NAMING_BEHAVIOR_VERSION",
    "Name",
    "NameProjection",
    "Operation",
    "OperationCancelled",
    "OperationResult",
    "OperationStatus",
    "PLANNING_BEHAVIOR_VERSION",
    "PLUGIN_API_VERSION",
    "PUBLIC_API_VERSION",
    "PluginCategory",
    "PluginDescriptor",
    "PluginRegistry",
    "PluginTrust",
    "SELECTION_BEHAVIOR_VERSION",
    "Schema",
    "SemanticId",
    "SemanticVersion",
    "SourceIdentity",
    "SourceKind",
    "SourcePosition",
    "SourceSpan",
    "validate_contract",
]
