from .api import CancellationToken, OperationCancelled, OperationResult, OperationStatus
from .diagnostics import (
    Diagnostic,
    Diagnostics,
    DiagnosticSeverity,
    SourceIdentity,
    SourceKind,
    SourcePosition,
    SourceSpan,
)
from .generation import (
    DEFAULT_SELECTOR_REGISTRY,
    SelectionCardinality,
    SelectionContext,
    SelectorDescriptor,
    SelectorRegistry,
)
from .ir import (
    Contract,
    ContractValidator,
    Group,
    Name,
    NameProjection,
    Operation,
    Schema,
    SemanticId,
    contract_from_document,
    contract_from_json,
    contract_from_yaml,
    contract_to_document,
    contract_to_json,
    contract_to_yaml,
    validate_contract,
)
from .plugins import PluginCategory, PluginDescriptor, PluginRegistry, PluginTrust
from .versions import (
    CORE_VERSION,
    DEFAULT_BEHAVIOR_VERSIONS,
    IR_API_VERSION,
    PLUGIN_API_VERSION,
    PUBLIC_API_VERSION,
    ApiVersion,
    BehaviorVersion,
    BehaviorVersions,
    Version,
)

__version__ = str(CORE_VERSION)

from .application import generate, generate_to_files

__all__ = [
    "ApiVersion",
    "BehaviorVersion",
    "BehaviorVersions",
    "CORE_VERSION",
    "CancellationToken",
    "Contract",
    "ContractValidator",
    "DEFAULT_BEHAVIOR_VERSIONS",
    "DEFAULT_SELECTOR_REGISTRY",
    "Diagnostic",
    "DiagnosticSeverity",
    "Diagnostics",
    "Group",
    "IR_API_VERSION",
    "Name",
    "NameProjection",
    "Operation",
    "OperationCancelled",
    "OperationResult",
    "OperationStatus",
    "PLUGIN_API_VERSION",
    "PUBLIC_API_VERSION",
    "PluginCategory",
    "PluginDescriptor",
    "PluginRegistry",
    "PluginTrust",
    "Schema",
    "SelectionCardinality",
    "SelectionContext",
    "SelectorDescriptor",
    "SelectorRegistry",
    "SemanticId",
    "SourceIdentity",
    "SourceKind",
    "SourcePosition",
    "SourceSpan",
    "Version",
    "contract_from_document",
    "contract_from_json",
    "contract_from_yaml",
    "contract_to_document",
    "contract_to_json",
    "contract_to_yaml",
    "generate",
    "generate_to_files",
    "validate_contract",
]
