from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

from codepotg.domain.ir import (
    AccessFacet,
    Compensation,
    Contract,
    ContractValidator,
    Documentation,
    Event,
    EventEffect,
    EventsFacet,
    ExecutionFacet,
    ExecutionHook,
    ExecutionPhase,
    FieldCapabilities,
    FieldConstraints,
    FieldLifecycle,
    FieldQuery,
    FieldReference,
    FieldVisibility,
    FieldWriteMode,
    FrozenObject,
    FrozenValue,
    Group,
    GroupFacets,
    GuidanceKind,
    GuidanceNote,
    HttpFacet,
    JsonScalar,
    KernelData,
    Name,
    NameProjection,
    Operation,
    OperationEffects,
    OperationFacets,
    OperationFailure,
    OperationOutput,
    Policy,
    Presentation,
    PresentationChannel,
    PresentationEntry,
    Provenance,
    QueryOperator,
    Schema,
    SchemaField,
    SchemaKind,
    SchemaUse,
    SemanticId,
    StorageFieldMapping,
    StorageMapping,
    StorageNamespace,
    TagSet,
    TriggerFacet,
    TriggerKind,
    TypeExpression,
    TypeKind,
    ValueSource,
    View,
    ViewTrigger,
    Workflow,
    WorkflowDecisionCase,
    WorkflowFacets,
    WorkflowStep,
    WorkflowStepKind,
    WorkflowTransition,
    pluralize,
    singularize,
    type_references,
    validate_contract,
    walk_groups,
    walk_views,
    walk_workflow_steps,
)

_CODEC_EXPORTS = {
    "IrCodecError",
    "contract_from_document",
    "contract_from_json",
    "contract_from_yaml",
    "contract_to_document",
    "contract_to_json",
    "contract_to_yaml",
    "validate_transport",
}

if TYPE_CHECKING:
    from .codec import (
        IrCodecError,
        contract_from_document,
        contract_from_json,
        contract_from_yaml,
        contract_to_document,
        contract_to_json,
        contract_to_yaml,
        validate_transport,
    )


def __getattr__(name: str) -> Any:
    if name not in _CODEC_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(".codec", __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))


__all__ = [
    "AccessFacet",
    "Compensation",
    "Contract",
    "ContractValidator",
    "Documentation",
    "Event",
    "EventEffect",
    "EventsFacet",
    "ExecutionFacet",
    "ExecutionHook",
    "ExecutionPhase",
    "FieldCapabilities",
    "FieldConstraints",
    "FieldLifecycle",
    "FieldQuery",
    "FieldReference",
    "FieldVisibility",
    "FieldWriteMode",
    "FrozenObject",
    "FrozenValue",
    "Group",
    "GroupFacets",
    "GuidanceKind",
    "GuidanceNote",
    "HttpFacet",
    "IrCodecError",
    "JsonScalar",
    "KernelData",
    "Name",
    "NameProjection",
    "Operation",
    "OperationEffects",
    "OperationFacets",
    "OperationFailure",
    "OperationOutput",
    "Policy",
    "Presentation",
    "PresentationChannel",
    "PresentationEntry",
    "Provenance",
    "QueryOperator",
    "Schema",
    "SchemaField",
    "SchemaKind",
    "SchemaUse",
    "SemanticId",
    "StorageFieldMapping",
    "StorageMapping",
    "StorageNamespace",
    "TagSet",
    "TriggerFacet",
    "TriggerKind",
    "TypeExpression",
    "TypeKind",
    "ValueSource",
    "View",
    "ViewTrigger",
    "Workflow",
    "WorkflowDecisionCase",
    "WorkflowFacets",
    "WorkflowStep",
    "WorkflowStepKind",
    "WorkflowTransition",
    "contract_from_document",
    "contract_from_json",
    "contract_from_yaml",
    "contract_to_document",
    "contract_to_json",
    "contract_to_yaml",
    "pluralize",
    "singularize",
    "type_references",
    "validate_contract",
    "validate_transport",
    "walk_groups",
    "walk_views",
    "walk_workflow_steps",
]
